### PR TITLE
TF generation is now provider-agnostic, plus GCP/Kube/Azure examples

### PR DESCRIPTION
**Pull request by scottyw**
This commit separates the bridge and generation out of providers and gives 4 examples of generated providers that make use of the bridge (AWS/GCP/Azure/Kubenerete).

To generate, first modify and run "tf-gen". Once that is done, modify and run "pp-gen".

### CODE REVIEW

**Comment by jdwelch** [comment]
Needs licence update

**Comment by scottyw** [comment]
Yep, every time ... the change is pushed.

**Comment by kenazk** [comment]
Looks good. Merged.

**Comment by jdwelch** [comment]
ヽ(•‿•)ノ

**Pull request merged**
