### PR TITLE
Remove AWS plugin

### PR DESCRIPTION
**Pull request by scottyw**
Per our discussion in Slack, the example AWS plugin and associated workflows are now out to pasture in https://github.com/lyraproj/aws-example.

This PR removes the plugin/workflows from Lyra and makes the consequent changes, like updating the docs, updating the TS example and removing corresponding generated types.

As a freebie, the Makefile no longer hardcodes the list of TF plugins.

### CODE REVIEW

**Comment by scottyw** [comment]
I tagged a lot of reviewers on this, just want to be sure everyone is happy to proceed. Thanks!

**Comment by scottyw** [comment]
Let's hold off merging and talk this afternoon? 

I agree that your 1, 2 and 3 are important but I suppose I feel like we're not losing the plugin, just deemphasising it as content you should be using. We could be more explicit about that in the README perhaps? The main reason to remove is that it's very limited and I think we don't want people to use it.

**Comment by jdwelch** [comment]
Maybe talk about it in the README (what it is, why it's interesting, etc) but keep in new repo?

**Comment by scottyw** [comment]
After some discussion we've concluded that we'll keep the AWS content for now, build some better generic examples then send AWS to the farm once that replacement content exists.

**Pull request closed without merging**
